name: Build Protthapan GCS Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout source with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Qt 6.8.3
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.3"
          host: "windows"
          target: "desktop"
          arch: "win64_msvc2022_64"
          cache: "true"

      - name: Setup MSVC 2022
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        run: choco install ninja -y

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: pwsh
        run: |
          cmake --build build --config Release --parallel 2

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: Protthapan-GCS-Windows-Build
          path: build